version: '3.8'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      container_name: postgres_data
      image: postgres:latest
      user: root
      ports: 
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      container_name: keycloak
      image: jboss/keycloak:16.1.1
      ports: 
        - "8403:8080"
      # command:
      # - COPY ./requiredaction/target/dasniko.keycloak-requiredaction.jar /opt/jboss/keycloak/standalone/deployments/
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres_data
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        DB_SCHEMA: public
        DB_PORT: 5432
        # KEYCLOAK_USER: admin
        # KEYCLOAK_PASSWORD: password
        KEYCLOAK_IMPORT: /tmp/config/keycloak/realms/trawell.json
        KEYCLOAK_FEATURES: 'declarative_user_profile'
        JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.declarative_user_profile=enabled"
      volumes:
      # - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
      - type: bind
        source: ./config/keycloak/realms
        target: /tmp/config/keycloak/realms
      - type: bind
        source: ./themes/custom
        target: /opt/jboss/keycloak/themes/custom
      depends_on:
        - postgres
      restart: always
 
  krakend:
      image: devopsfaith/krakend:latest
      container_name: krakend_gateway
      command: run -d -c /etc/krakend/krakend.json
      ports:
        - "9000:9000"
      volumes:
        - ./gateway:/etc/krakend

 